'use client';
import { useEffect, useState } from 'react';
import { quizQuestions, resolveQuiz, type QuizResult } from './quizEngine';
import { races, classes, backgrounds } from './catalog';
import { subclasses } from './characterRules';
const storageKey='herolist.quiz.v1.2';
export function HeroQuiz({onClose,onCreate}:{onClose:()=>void;onCreate:(result:QuizResult,level:number)=>void}){
 const [answers,setAnswers]=useState<number[]>([]),[index,setIndex]=useState(0),[level,setLevel]=useState(1),[loaded,setLoaded]=useState(false),[error,setError]=useState('');
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(storageKey)||'null');if(Array.isArray(saved)&&saved.length<=20&&saved.every((a,i)=>Number.isInteger(a)&&quizQuestions[i].answers[a])){setAnswers(saved);setIndex(saved.length);}}catch{}setLoaded(true);},[]);
 useEffect(()=>{if(loaded)try{localStorage.setItem(storageKey,JSON.stringify(answers));}catch{}},[answers,loaded]);
 const result=index===20?resolveQuiz(answers):null;
 return <section className="hero-quiz"><header><button onClick={onClose}>← Главное меню</button><span>Какой из тебя герой?</span><strong>{Math.min(index+1,20)} / 20</strong></header><progress max={20} value={index}/>
 {result?<><h1>Твой герой</h1><div className="quiz-result">{[["Раса",races.find(x=>x.id===result.raceId)?.name],["Класс",classes.find(x=>x.id===result.classId)?.name],["Предыстория",backgrounds.find(x=>x.id===result.backgroundId)?.name],["Подкласс",subclasses[result.classId].options.find(x=>x.id===result.subclassId)?.name]].map(([label,value])=><div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div><p>Ответы о привычках, решениях и отношении к другим определили происхождение героя. Последние три ответа уточнили его путь.</p><label className="quiz-level">Уровень персонажа<select value={level} onChange={e=>setLevel(Number(e.target.value))}>{Array.from({length:20},(_,i)=><option key={i} value={i+1}>{i+1}</option>)}</select></label>{level<result.subclassUnlockLevel&&<p role="status">Подкласс станет доступен на уровне {result.subclassUnlockLevel}. Рекомендация сохранится в персонаже.</p>}<p>Характеристики, навыки, заклинания и снаряжение будут заполнены автоматически. Готового героя можно редактировать.</p>{error&&<p role="alert">{error}</p>}<button className="primary-action" onClick={()=>{try{onCreate(result,level);localStorage.removeItem(storageKey);}catch(e){setError(e instanceof Error?e.message:'Не удалось создать персонажа.');}}}>Создать готового персонажа</button><button onClick={()=>{setAnswers([]);setIndex(0);setError('');}}>Пройти заново</button><details><summary>Почему такой результат?</summary><p>Раса, класс и предыстория учитывают все первые 17 ответов. Подкласс выбирается среди путей полученного класса. При одинаковых ответах результат остаётся тем же.</p><p>Характеристики расставляются по потребностям класса. Повышения развивают основные характеристики; хиты растут на фиксированное среднее. Навыки и инструменты выбираются с учётом уже освоенных владений.</p></details></>:<><h1>{quizQuestions[index].text}</h1><div className="quiz-answers">{quizQuestions[index].answers.map((a,i)=><button key={i} onClick={()=>{setAnswers([...answers.slice(0,index),i]);setIndex(index+1);}}><span>{i+1}</span>{a.text}</button>)}</div>{index>0&&<button onClick={()=>setIndex(index-1)}>← Назад</button>}</>}
 </section>;
}
