'use client';
import { createContext, useContext, useMemo, useState, type ReactNode } from 'react';
import { newHomebrew, homebrewTypeLabels, type HomebrewElement, type HBChoice } from './homebrew';
import { conditionFormula, createChoiceOption, editableHomebrew, effectLabel, homebrewRelations, readConditions, type HBCondition } from './homebrewRelations';
import type { ExportCharacter } from './exportFormats';
import { hbEnabled, hbValue, homebrewChoiceReason } from './homebrewEngine';
import { HomebrewCommandInput } from './HomebrewCommandInput';

export type HBEditingSession={elements:HomebrewElement[];character:ExportCharacter;change:(patch:Partial<HomebrewElement>,related?:HomebrewElement[])=>void;patchElement:(id:string,patch:Partial<HomebrewElement>,related?:HomebrewElement[])=>void;renderMechanics:(element:HomebrewElement,patch:(p:Partial<HomebrewElement>,related?:HomebrewElement[])=>void,depth:number)=>ReactNode};
export const HBEditingContext=createContext<HBEditingSession|null>(null);
function useSession(){const value=useContext(HBEditingContext);if(!value)throw Error('Homebrew editing session missing');return value;}
export function NamedReference({value,onChange,options,label}:{value:string;onChange:(id:string)=>void;options:{id:string;name:string}[];label:string}){
 const [query,setQuery]=useState('');const [expanded,setExpanded]=useState(false);
 const unique=[...new Map(options.map(option=>[option.id,option])).values()];
 const selected=unique.find(option=>option.id===value);
 return <div className="hb-field hb-named-reference"><span>{label}</span><button type="button" aria-expanded={expanded} onClick={()=>setExpanded(!expanded)}>{selected?.name|| (value?'Не найдено: '+value:'Выбрать по названию')}</button>{expanded&&<div className="hb-reference-menu"><input aria-label={'Поиск: '+label} placeholder="Поиск по названию" value={query} onChange={event=>setQuery(event.target.value)}/><div className="hb-id-results">{unique.filter(option=>(option.name+' '+option.id).toLowerCase().includes(query.toLowerCase())).slice(0,60).map(option=><button type="button" key={option.id} onClick={()=>{onChange(option.id);setExpanded(false);setQuery('');}}>{option.name}</button>)}</div></div>}{value&&<details className="hb-technical"><summary>Техническая ссылка</summary><code>{value}</code></details>}</div>;
}
export function ConditionEditor({value,onChange,elements,label='Когда действует'}:{value:string;onChange:(formula:string)=>void;elements:HomebrewElement[];label?:string}){
 const parsed=readConditions(value),flat=editableHomebrew(elements);
 const change=(rows:HBCondition[],mode=parsed?.mode||'all')=>onChange(conditionFormula(rows,mode));
 return <section className="hb-condition-editor"><strong>{label}</strong>{parsed?<><div className="hb-condition-rows">{parsed.rows.map((row,index)=><div key={index} className="hb-condition-row"><select aria-label="Вид условия" value={row.kind} onChange={event=>change(parsed.rows.map((r,i)=>i===index?{kind:event.target.value as HBCondition['kind'],id:flat[0]?.id,level:1}:r))}><option value="selected">Выбран вариант / элемент</option><option value="level">Уровень персонажа не ниже</option><option value="classLevel">Уровень класса не ниже</option></select>{row.kind==='selected'?<NamedReference label="Выбран элемент" value={row.id||''} options={flat} onChange={id=>change(parsed.rows.map((r,i)=>i===index?{...r,id}:r))}/>:<input aria-label="Минимальный уровень условия" type="number" min={1} max={20} value={row.level||1} onChange={event=>change(parsed.rows.map((r,i)=>i===index?{...r,level:Number(event.target.value)}:r))}/>}<button type="button" onClick={()=>change(parsed.rows.filter((_,i)=>i!==index))}>Убрать условие</button></div>)}</div>{!parsed.rows.length&&<p>Действует постоянно.</p>}{parsed.rows.length>1&&<select aria-label="Как проверять условия" value={parsed.mode} onChange={event=>change(parsed.rows,event.target.value as 'all'|'any')}><option value="all">Выполнены все условия</option><option value="any">Выполнено любое условие</option></select>}<div className="hb-toolbar"><button type="button" onClick={()=>change([...parsed.rows,{kind:'level',level:5}])}>+ Условие уровня</button>{flat.length>0&&<button type="button" onClick={()=>change([...parsed.rows,{kind:'selected',id:flat[0].id}])}>+ Условие выбора</button>}</div></>:<p>Сложное условие сохранено без изменений. Оно редактируется в формуле ниже.</p>}<details><summary>Формула условия</summary><HomebrewCommandInput label={label} value={value} onChange={onChange}/></details></section>;
}
export function RelationshipPanel({element,onChange,compact=false}:{element:HomebrewElement;onChange:(p:Partial<HomebrewElement>)=>void;compact?:boolean}){
 const session=useSession(),flat=editableHomebrew(session.elements);
 const [mode,setMode]=useState('requires');
 const dependent=flat.filter(other=>other.id!==element.id&&other.requirements?.some(r=>r.id===element.id));
 const granted=(element.effects||[]).filter(effect=>effect.type.startsWith('grant_')&&effect.id);
 const connect=(id:string)=>{
  if(mode==='requires')onChange({requirements:[...(element.requirements||[]).filter(r=>r.id!==id),{type:'selected_feature',id}]});
  else if(mode==='dependent'){const target=flat.find(row=>row.id===id);if(target)session.patchElement(id,{requirements:[...(target.requirements||[]).filter(r=>r.id!==element.id),{type:'selected_feature',id:element.id}]});}
  else {const target=flat.find(row=>row.id===id);const type=target?.type==='spell'?'grant_spell':target?.type==='resource'?'grant_resource':target?.type==='attack'?'grant_attack':'grant_feature';onChange({effects:[...element.effects||[],{type,id}]});}
 };
 return <section className="hb-relationships"><h4>Условия и последствия</h4><div className="hb-relation-columns"><div><strong>Требует выбранного элемента</strong>{!(element.requirements||[]).length&&<p className="hb-level-empty">Без требований к выбору.</p>}{(element.requirements||[]).map((r,index)=><div className="hb-relation-line" key={index}><span>{flat.find(row=>row.id===r.id)?.name||r.id}</span><button type="button" aria-label={'Убрать требование '+(flat.find(row=>row.id===r.id)?.name||r.id)} onClick={()=>onChange({requirements:element.requirements?.filter((_,i)=>i!==index)})}>Убрать</button></div>)}{(element.requirements?.length||0)>1&&<small>Нужны все перечисленные элементы.</small>}</div><div><strong>Открывает выбор способностей</strong>{!dependent.length&&<p className="hb-level-empty">Зависимых вариантов пока нет.</p>}{dependent.map(row=><div className="hb-relation-line" key={row.id}><span>{row.name}{row.level?` · с ${row.level} уровня`:''}</span><button type="button" onClick={()=>session.patchElement(row.id,{requirements:row.requirements?.filter(r=>r.id!==element.id)})}>Убрать связь</button></div>)}</div></div>{!compact&&<><strong>Выдаёт автоматически</strong>{granted.map((effect,index)=><p key={index}>{effectLabel(effect,flat)}{effect.when?` · ${effect.when}`:''}</p>)}</>}<div className="hb-relation-add"><select aria-label="Смысл новой связи" value={mode} onChange={event=>setMode(event.target.value)}><option value="requires">Требует выбранного элемента</option><option value="dependent">Открывает выбор другого элемента</option><option value="grant">Выдаёт автоматически</option></select><NamedReference label="Добавить связь" value="" options={flat.filter(row=>row.id!==element.id&& (mode!=='dependent'||session.elements.some(e=>e.id===row.id)&&(row.type==='ability'||row.type==='feat')))} onChange={connect}/></div></section>;
}
export function ChoiceEditor({owner,choice,onChange,onRemove,onAddStage,depth=0}:{owner:HomebrewElement;choice:HBChoice;onChange:(choice:HBChoice,related?:HomebrewElement[])=>void;onRemove:()=>void;onAddStage?:()=>void;depth?:number}){
 const session=useSession();const flat=editableHomebrew(session.elements);
 const [creating,setCreating]=useState(false),[name,setName]=useState(''),[selected,setSelected]=useState(choice.from[0]||''),[map,setMap]=useState(false),[level,setLevel]=useState(choice.level||1);
 const options=choice.from.map(id=>flat.find(element=>element.id===id)).filter((row):row is HomebrewElement=>!!row);
 const option=options.find(row=>row.id===selected)||options[0];
 const patch=(p:Partial<HBChoice>)=>onChange({...choice,...p});
 const milestones=(owner.choices||[]).filter(row=>row.id===choice.id||!!choice.choiceGroup&&row.choiceGroup===choice.choiceGroup).sort((a,b)=>(a.level||1)-(b.level||1));
 const visibleEffects=option?.effects||[];
 const classId=owner.type==='class'?owner.id:owner.parentClassId;
 const preview={...session.character,level,classes:classId?[{classId:classId.replace('official:class:',''),level,acquiredAtCharacterLevel:1}]:undefined,className:classId||session.character.className,homebrew:{...session.character.homebrew,entities:session.elements,activeIds:[...new Set([owner.id,...(classId?[classId]:[])])],choices:{...session.character.homebrew?.choices,[choice.id]:option?[option.id]:[]}}} as ExportCharacter;
 const previewBlock=option?homebrewChoiceReason(preview,owner,choice,option,session.elements):'';
 return <section className="hb-unified-choice"><div className="hb-choice-settings"><label>Название выбора<input aria-label="Название выбора" value={choice.name} onChange={event=>patch({name:event.target.value})}/></label><label>Сколько выбрать<input aria-label="Количество вариантов выбора" type="number" min={1} max={50} value={choice.count} onChange={event=>patch({count:Number(event.target.value)})}/></label><label>С уровня<input aria-label="Уровень выбора" type="number" min={1} max={20} value={choice.level||1} onChange={event=>patch({level:Number(event.target.value)})}/></label><label>Тип вариантов<select aria-label="Тип выбора" value={choice.type} onChange={event=>patch({type:event.target.value})}>{Object.entries({ability:'Вариант способности',feature:'Способность',feat:'Черта',spell:'Заклинание',item:'Предмет',skill:'Навык',expertise:'Экспертность',language:'Язык',tool:'Инструмент',option:'Вариант'}).map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label></div>
 <div className="hb-choice-milestones"><strong>Прогрессия этой способности</strong>{milestones.map(row=><span key={row.id}>{row.level||1} ур. · выбрать {row.count}</span>)}{onAddStage&&<button type="button" onClick={onAddStage}>+ Следующий этап выбора</button>}</div><details><summary>Повторные выборы и запрет повторов</summary><label>Общая ветка<input aria-label="Группа выбора" value={choice.choiceGroup||''} onChange={event=>patch({choiceGroup:event.target.value||undefined})}/></label><label><input type="checkbox" checked={!!choice.uniqueAcrossGroup} onChange={event=>patch({uniqueAcrossGroup:event.target.checked,choiceGroup:event.target.checked?choice.choiceGroup||choice.id:choice.choiceGroup})}/>Не повторять варианты в этой ветке</label></details>
 <div className="hb-option-tabs">{options.map(row=><button type="button" key={row.id} aria-pressed={row.id===option?.id} onClick={()=>setSelected(row.id)}>{row.name}<small>{row.level&&row.level>(choice.level||1)?`С ${row.level} уровня`:''}</small></button>)}</div>
 {choice.from.filter(id=>!flat.some(row=>row.id===id)).map(id=><p role="alert" key={id}>Не найден вариант: {id} <button type="button" onClick={()=>patch({from:choice.from.filter(ref=>ref!==id)})}>Убрать ссылку</button></p>)}
 <div className="hb-toolbar"><button type="button" onClick={()=>setCreating(!creating)}>+ Создать вариант здесь</button><details><summary>Прикрепить существующий вариант</summary><NamedReference label="Добавить вариант в этот выбор" value="" options={flat.filter(row=>row.id!==owner.id&&!choice.from.includes(row.id)&& (['ability','feature','option'].includes(choice.type)?row.type==='ability':row.type===choice.type))} onChange={id=>{patch({from:[...choice.from,id]});setSelected(id);}}/></details><button type="button" aria-pressed={map} onClick={()=>setMap(!map)}>Карта связей выбора</button></div>
 {creating&&<div className="hb-inline-create"><label>Название нового варианта<input aria-label="Название нового варианта" value={name} onChange={event=>setName(event.target.value)}/></label><button type="button" disabled={!name.trim()} onClick={()=>{const next=createChoiceOption(owner,choice,name.trim());onChange({...choice,from:[...choice.from,next.id]},[next]);setSelected(next.id);setName('');setCreating(false);}}>Создать и добавить в выбор</button></div>}
 {option&&<article className="hb-choice-option-editor" key={option.id}><header><strong>{option.name}</strong><span>Вариант выбора «{choice.name}»</span></header><label>Название варианта<input aria-label="Название варианта" value={option.name} onChange={event=>session.patchElement(option.id,{name:event.target.value})}/></label><label>Описание варианта<HomebrewCommandInput label="Описание варианта" multiline value={option.description} onChange={description=>session.patchElement(option.id,{description})}/></label><label>Доступен с уровня<input aria-label="Уровень варианта" type="number" min={1} max={20} value={option.level||choice.level||1} onChange={event=>session.patchElement(option.id,{level:Number(event.target.value)})}/></label>
 <div className="hb-choice-preview"><div className="hb-toolbar"><strong>Результат выбора</strong><label>На уровне<input aria-label="Уровень предпросмотра выбора" type="number" min={1} max={20} value={level} onChange={event=>setLevel(Number(event.target.value))}/></label></div>{previewBlock?<p>Пока недоступен: {previewBlock}.</p>:<>{visibleEffects.map((effect,index)=><p key={index}>{hbEnabled(preview,effect,option)?'✓ Действует: ':'○ Не действует: '}{effectLabel(effect,flat)}{(effect.formula!==undefined||typeof effect.value==='string')&&<strong> = {hbValue(preview,effect.formula??effect.value,option.id)}</strong>}{effect.when&&<small> · Условие: {effect.when}</small>}</p>)}{!visibleEffects.length&&<p>{option.summary||option.description||'Добавьте описание или механический эффект.'}</p>}{option.resources?.map(row=><p key={row.id}>Ресурс: {row.name} · максимум {row.max}</p>)}{option.attacks?.map(row=><p key={row.id}>Атака: {row.name}</p>)}</>}</div>
 <RelationshipPanel element={option} onChange={p=>session.patchElement(option.id,p)}/>
 <details><summary>Эффекты, ресурсы, атаки и вложенные выборы варианта</summary>{depth<8?session.renderMechanics(option,(p,related)=>session.patchElement(option.id,p,related),depth+1):<p>Откройте этот элемент отдельно для дальнейшего редактирования.</p>}</details><button type="button" onClick={()=>patch({from:choice.from.filter(id=>id!==option.id)})}>Убрать из выбора</button>
 </article>}{map&&<RelationsMap element={owner} initialFocus={option?.id||owner.id}/>}
 <button type="button" className="hb-danger" onClick={onRemove}>Удалить этот этап выбора</button></section>;
}
export function ChoicesEditor({draft,update,depth=0}:{draft:HomebrewElement;update:(p:Partial<HomebrewElement>,related?:HomebrewElement[])=>void;depth?:number}){
 const choices=draft.choices||[];
 return <section className="hb-choice-collection"><h3>Выборы внутри «{draft.name||'элемента'}» · {choices.length}</h3>{choices.map(choice=><details key={choice.id} className="hb-choice-progression-card" open><summary><span>{choice.name}</span><small>{choice.count} из {choice.from.length}</small></summary><ChoiceEditor owner={draft} choice={choice} depth={depth} onChange={(next,related)=>update({choices:choices.map(row=>row.id===choice.id?next:row)},related)} onAddStage={()=>{const group=choice.choiceGroup||choice.id;update({choices:[...choices.map(row=>row.id===choice.id?{...row,choiceGroup:group}:row),{...choice,id:newHomebrew('ability').id,choiceGroup:group,level:Math.min(20,(choice.level||1)+1)}]});}} onRemove={()=>update({choices:choices.filter(row=>row.id!==choice.id)})}/></details>)}<button type="button" onClick={()=>update({choices:[...choices,{id:newHomebrew('ability').id,name:'Новый выбор',type:'ability',count:1,from:[],level:draft.level||1}]})}>+ Добавить выбор внутри элемента</button></section>;
}
export function RelationsMap({element,initialFocus}:{element:HomebrewElement;initialFocus?:string}){
 const session=useSession(),[focus,setFocus]=useState(initialFocus||element.id);
 const graph=useMemo(()=>homebrewRelations(session.elements),[session.elements]);
 const current=graph.nodes.find(node=>node.id===focus)||graph.nodes.find(node=>node.id===element.id);
 if(!current)return null;
 const incoming=graph.edges.filter(edge=>edge.to===current.id),outgoing=graph.edges.filter(edge=>edge.from===current.id);
 const subject=editableHomebrew(session.elements).find(row=>row.id===current.entityId);
 const list=(edges:typeof incoming,direction:'from'|'to')=><div className="hb-graph-lane">{!edges.length&&<p className="hb-level-empty">Связей пока нет</p>}{edges.map((edge,index)=>{const target=graph.nodes.find(node=>node.id===edge[direction]);return <div className="hb-graph-branch" key={index}><span className="hb-graph-edge">→ {edge.label}{edge.condition&&<small>{edge.condition}</small>}</span><button type="button" className="hb-graph-node" onClick={()=>setFocus(edge[direction])}>{target?.name||edge[direction]}<small>{homebrewTypeLabels[target?.kind as HomebrewElement['type']]||({choice:'Выбор',effect:'Эффект',resources:'Ресурс',attacks:'Атака',actions:'Действие'} as Record<string,string>)[target?.kind||'']||'Ссылка'}</small></button></div>})}</div>;
 return <section className="hb-relations-map" aria-label="Карта связей"><header><h3>Карта связей</h3><button type="button" onClick={()=>setFocus(element.id)}>К текущему элементу</button></header><p>Нажмите узел, чтобы увидеть его связи и изменить условия.</p><div className="hb-graph-grid"><section><h4>От чего зависит</h4>{list(incoming,'from')}</section><div className="hb-graph-current"><strong>{current.name}</strong><small>Выбранный узел</small></div><section><h4>На что влияет</h4>{list(outgoing,'to')}</section></div>{subject&&(session.elements.some(row=>row.id===subject.id)?<RelationshipPanel element={subject} onChange={patch=>session.patchElement(subject.id,patch)} compact/>:<details><summary>Механика способности и условия эффектов</summary>{session.renderMechanics(subject,(patch,related)=>session.patchElement(subject.id,patch,related),0)}</details>)}</section>;
}
